module.exports = [
    // When using local faye, you need to build faye manually with jake
    // {name: "faye", gitUrl: "git://github.com/jcoglan/faye.git", branch: "0.8.x"},
    // {name: "faye-websocket", gitUrl: "git://github.com/jcoglan/faye-websocket-node.git"},
    {name: "sinon", gitUrl: "git://github.com/cjohansen/Sinon.JS.git"},
    "buster-util",
    "buster-user-agent-parser",
    "buster-terminal",
    "buster-core",
    "buster-glob",
    "buster-assertions",
    "buster-format",
    "buster-promise",
    "buster-module-loader",
    "buster-evented-logger",
    "buster-test",
    "sinon-buster",
    "buster-resources",
    "buster-capture-server",
    "buster-bayeux-emitter",
    "buster-configuration",
    "buster-client",
    "buster-args",
    "buster-stdio-logger",
    "buster-cli",
    "buster-test-cli",
    "buster-static",
    "buster"
];
