#!/usr/bin/env node
var buster = require("buster-node");

buster.testRunner.onCreate(function (runner) {
    runner.on("suite:end", function (results) {
        process.nextTick(function () {
            process.exit(results.ok ? 0 : 1);
        });
    });
});

require("./test/fn-helpers-test.js");
require("./test/dev-util-test.js");
require("./test/connectives-test.js");
